Homework lesson33
ViktorRomanenko05/JavaAIT pull request #8
Opened 2024-05-16 05:01 UTC by ViktorRomanenko05

2024-05-16 12:38 UTC, zimmermann2013 requested changes

2024-05-16 12:38 UTC, zimmermann2013 commented on src/main/java/homeworkLesson33/ClothingManager.java
> +            System.out.println("Clothing item was successfully added");
Здесь можно добавить название добавляемой вещи, что бы различать если 3 различных вещи будут друг за другом добавлены

2024-05-16 12:38 UTC, zimmermann2013 commented on src/main/java/homeworkLesson33/ClothingManager.java
> +                    iterator.remove();
Я бы добавил здесь текстовое уведомление о том, что вещь  и с каким названием удалена

2024-05-16 12:38 UTC, zimmermann2013 commented on src/main/java/homeworkLesson33/ClothingItem.java
> +    private String type;
В идеале можно было в Enum вынести

2024-05-16 20:41 UTC, ViktorRomanenko05 commented on src/main/java/homeworkLesson33/ClothingManager.java
> +            System.out.println("Clothing item was successfully added");
Исправлено.
В сообщение добавлены тип вещи и ее название.

2024-05-16 20:45 UTC, ViktorRomanenko05 commented on src/main/java/homeworkLesson33/ClothingManager.java
> +                    iterator.remove();
Исправлено.
Добавлена строка с соответствующим текстом и атрибутами.

2024-05-16 21:14 UTC, ViktorRomanenko05 commented on src/main/java/homeworkLesson33/ClothingItem.java
> +    private String type;
enum - действительно очень удобный инструмент, но я не использовал его в данном случае по следующим причинам:

1. Старался выполнять задачу в максимальном соответствии заданию (там указано, что поле - String). Для меня это полезно так как заметил, что часто отклонялся от условия в предыдущих заданиях.

2. В случае с полем "name" (название вещи) - не совсем понял, что имеется в виду - это бренд, или название модели, или всё вместе. Это с высокой вероятностью приведет к очень большому количеству вариантов и enum будет целесообразен только в учебных целях, как пример.

3. То же самое с полем "type". Даже если убрать различные аксессуары и обувь, то и в базовом варианте получим примерно это:

        1.     Куртка
	2.	Штаны
	3.	Рубашка
	7.	Платье
	8.	Блузка
	9.	Жилет
	10.	Пиджак
	11.	Тренч
	12.	Джинсы
	13.	Шорты
	14.	Свитер
	15.	Кардиган
	16.	Топ
	17.	Туника
	18.	Сарафан
	19.	Юбка
	20.	Костюм
	21.	Пальто
	22.	Пончо
	23.	Капри
	24.	Леггинсы
	25.	Комбинезон
	26.	Ветровка
	27.	Кожаная куртка
	28.	Пуховик
	29.	Носки
	30.	Нижнее бельё
	31.	Купальник
	32.	Спортивная форма
	33.	Халат
	34.  Шапка
	35.  Шарф

Но энумы использованы в тестировании, как поставщики входящих данных для теста.

Спасибо за ревью и полезные замечания.

2024-05-23 06:26 UTC, zimmermann2013 approved these changes

2024-05-23 07:14 UTC, merged